version: '3.8'
services:
  rtsp-mariadb:
    restart: always
    image: mariadb:latest
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=SuperDuperSecretPass666
      - MYSQL_DATABASE=cameras_db
      - MYSQL_ROOT_HOST=%

  rtsp-backend:
    depends_on:
      - rtsp-mariadb
    restart: always
    build: ./rtsp-backend
    ports:
      - '8080:8080'
    expose:
      - '8080'
    working_dir: '/rtsp-backend'
    entrypoint: '/bin/bash wait-for rtsp-mariadb:3306 -t 0 -- java -jar cameras.jar'
    environment:
      - spring.datasource.url=jdbc:mariadb://rtsp-mariadb:3306/cameras_db
      - spring.datasource.username=root
      - spring.datasource.password=SuperDuperSecretPass666

  rtsp-locator:
    depends_on:
      - rtsp-mariadb
      - rtsp-backend
    build: ./rtsp-locator
    working_dir: /rtsp-locator
    entrypoint: '/bin/bash wait-for rtsp-backend:8080 -t 0 -- python3 -u /rtsp-locator/rtsp-spyglass.py --country-code CZ --import-endpoint http://rtsp-backend:8080/cameras/import'

  rtsp-health-checker:
    depends_on:
      - rtsp-mariadb
      - rtsp-backend
    build: ./rtsp-health-checker
    working_dir: /rtsp-health-check
    volumes:
      - '$PWD:/rtsp-health-checker'
    entrypoint: '/bin/bash wait-for rtsp-backend:8080 -t 0 -- python3 -u /rtsp-health-check/rtsp-health-checker.py --sleep-timer 60 --rtsp-backend-url http://rtsp-backend:8080/ --daemon'